name: Docker-CI-CD-Pipeline

on: [push,pull_request]

jobs:
  build:
    name: Build-Docker-File
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REACT_APP_NAME: railway
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: install dependencies
        run: npm ci
      
      - name: run lint
        run: npm run lint
      
      - name: run tests
        run: npm test

      - name: build project
        run: npm run build
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Lowercase Repository Owner
        run: |
          echo "REPO_OWNER=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.actor }}'

      - uses: docker/build-push-action@v6.18.0
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/react-app-cicd:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/react-app-cicd:latest
          context: .

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.BUILD_IP }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.BUILDPUBKEY }}
          port: 22
          script: |
            OWNER="${{ github.actor }}"
            REPO_OWNER="${OWNER,,}"
            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
            docker pull ghcr.io/$REPO_OWNER/react-app-cicd:latest
            docker stop react-app-cicd || true
            docker rm react-app-cicd || true
            docker run -d --name react-app-cicd -p 80:80 ghcr.io/$REPO_OWNER/react-app-cicd:latest
