name: Legacy-CI-CD-Pipeline

on: [push,pull_request]

jobs:
  build:
    name: Build-and-Deploy
    runs-on: ubuntu-latest
    env:
      REACT_APP_NAME: railway
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependencies
        run: npm ci
          
      - name: run lint 
        run: npm run lint
      
  
      - name: run tests
        run: npm test
      
      - name: build project
        run: npm run build
  
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: dist
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: dist
      - name: Deploy to Railway
        run: |
          echo "deploying to server"
          echo "deploying to server"
          echo "deploying to server"
          